name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    environment:
      name: github-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare deploy folder using rsync
        run: |
          mkdir publish
          rsync -aL dist/ publish/
          # Debug: List any symlinks that may remain
          echo "Checking for symlinks before fix:"
          find publish -type l -ls || true

      - name: Fix symlinks
        run: |
          echo "Fixing symlinks in publish folder..."
          # For every symlink found in publish, replace it with its file content.
          find publish -type l -exec sh -c 'cat "$0" > "${0}.resolved" && mv "${0}.resolved" "$0"' {} \;
          echo "Verifying no symlinks remain:"
          if find publish -type l | read; then
            echo "Symlinks still exist!" && exit 1;
          else
            echo "All symlinks fixed."
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./publish

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
