name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    environment:
      name: github-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare deploy folder
        run: |
          mkdir publish
          cp -r dist/* publish/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./publish

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4


